import { FurnitureDefinition } from '../types/map'

export const TILE_SIZE = 32

export const DEFAULT_AVATAR = {
  skinColor: '#ffd1a4',
  hairStyle: 'short' as const,
  hairColor: '#2b2b2b',
  shirtType: 'tshirt' as const,
  shirtColor: '#4c6ef5',
  pantsColor: '#2c3e50',
  accessory: 'headphones' as const,
  accessoryColor: '#20c997',
}

export const FURNITURE_CATALOG: FurnitureDefinition[] = [
  // --- HABBO HOTEL ICONIC CATALOG (FURNI & RARES) ---
  {
    id: 'habbo_sofa_hc',
    name: 'Sofá de Clube HC (Habbo Club)',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_sofa_hc',
    iconColor: '#2b8a3e',
  },
  {
    id: 'habbo_dragon_lamp',
    name: 'Candeeiro Dragão de Fogo (Raro)',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_dragon_lamp',
    iconColor: '#e03131',
  },
  {
    id: 'habbo_duck_yellow',
    name: 'Pato Amarelo Habbo Clássico',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_duck_yellow',
    iconColor: '#fcc419',
  },
  {
    id: 'habbo_executive_desk',
    name: 'Mesa Executiva Habbo (Mogno)',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_executive_desk',
    iconColor: '#5c3a21',
  },
  {
    id: 'habbo_bar_counter',
    name: 'Balcão de Recepção / Bar Habbo',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_bar_counter',
    iconColor: '#a65228',
  },
  {
    id: 'habbo_drink_vending',
    name: 'Máquina de Refrigerante Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_drink_vending',
    iconColor: '#1971c2',
  },
  {
    id: 'habbo_teleport_door',
    name: 'Porta Teletransporte Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_teleport_door',
    iconColor: '#862e9c',
  },
  {
    id: 'habbo_plant_yucca',
    name: 'Planta Yucca Habbo Clássica',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_plant_yucca',
    iconColor: '#2f9e44',
  },
  {
    id: 'habbo_dj_deck',
    name: 'Cabine de DJ Habbo Sound',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_dj_deck',
    iconColor: '#be4bdb',
  },
  {
    id: 'habbo_pool_lounger',
    name: 'Espreguiçadeira de Piscina Habbo',
    category: 'habbo',
    width: 1,
    height: 2,
    isObstacle: false,
    spriteKey: 'habbo_pool_lounger',
    iconColor: '#38d9a9',
  },
  {
    id: 'habbo_tv_retro',
    name: 'TV de Tubo Retrô Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_tv_retro',
    iconColor: '#495057',
  },
  {
    id: 'habbo_sofa_plasto',
    name: 'Sofá Plasto Habbo Azul',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_sofa_plasto',
    iconColor: '#339af0',
  },

  // --- DESKS & WORKSPACES ---
  {
    id: 'desk_pc_single',
    name: 'Mesa com PC & Monitor',
    category: 'desks',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_pc_single',
    iconColor: '#4c6ef5',
  },
  {
    id: 'desk_mac_dual',
    name: 'Mesa Apple Dual Monitor',
    category: 'desks',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_mac_dual',
    iconColor: '#748ffc',
  },
  {
    id: 'desk_gamer_triple',
    name: 'Setup Gamer Triplo RGB',
    category: 'desks',
    width: 3,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_gamer_triple',
    iconColor: '#f06595',
  },
  {
    id: 'desk_simple_wood',
    name: 'Mesa de Madeira Simples',
    category: 'desks',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'desk_simple_wood',
    iconColor: '#d9480f',
  },

  // --- CHAIRS ---
  {
    id: 'chair_office_black',
    name: 'Cadeira de Escritório',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_office_black',
    iconColor: '#495057',
  },
  {
    id: 'chair_gamer_red',
    name: 'Cadeira Gamer Vermelha',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_gamer_red',
    iconColor: '#ff6b6b',
  },
  {
    id: 'chair_wooden',
    name: 'Cadeira de Madeira',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_wooden',
    iconColor: '#f59f00',
  },

  // --- MEETING & COLLABORATION ---
  {
    id: 'table_meeting_large',
    name: 'Mesa de Reunião Grande',
    category: 'meeting',
    width: 4,
    height: 2,
    isObstacle: true,
    spriteKey: 'table_meeting_large',
    iconColor: '#339af0',
  },
  {
    id: 'table_meeting_round',
    name: 'Mesa de Reunião Redonda',
    category: 'meeting',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'table_meeting_round',
    iconColor: '#22b8cf',
  },
  {
    id: 'whiteboard_stand',
    name: 'Quadro Branco / Lousa',
    category: 'meeting',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'whiteboard_stand',
    iconColor: '#f8f9fa',
  },
  {
    id: 'tv_presentation',
    name: 'Smart TV Apresentação',
    category: 'meeting',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'tv_presentation',
    iconColor: '#1098ad',
  },

  // --- LOUNGE & RELAX ---
  {
    id: 'sofa_orange_3seat',
    name: 'Sofá Laranja 3 Lugares',
    category: 'lounge',
    width: 3,
    height: 1,
    isObstacle: false,
    spriteKey: 'sofa_orange_3seat',
    iconColor: '#fd7e14',
  },
  {
    id: 'sofa_blue_2seat',
    name: 'Sofá Azul 2 Lugares',
    category: 'lounge',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'sofa_blue_2seat',
    iconColor: '#4dabf7',
  },
  {
    id: 'beanbag_purple',
    name: 'Puff Roxo Conforto',
    category: 'lounge',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'beanbag_purple',
    iconColor: '#be4bdb',
  },
  {
    id: 'coffee_table_round',
    name: 'Mesa de Centro',
    category: 'lounge',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'coffee_table_round',
    iconColor: '#e8590c',
  },
  {
    id: 'ping_pong_table',
    name: 'Mesa de Ping Pong',
    category: 'lounge',
    width: 3,
    height: 2,
    isObstacle: true,
    spriteKey: 'ping_pong_table',
    iconColor: '#40c057',
  },

  // --- DECOR & KITCHEN ---
  {
    id: 'coffee_machine_station',
    name: 'Estação de Café / Espresso',
    category: 'decor',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'coffee_machine_station',
    iconColor: '#862e9c',
  },
  {
    id: 'water_cooler',
    name: 'Bebedouro d\'Água',
    category: 'decor',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'water_cooler',
    iconColor: '#38d9a9',
  },
  {
    id: 'plant_pot_large',
    name: 'Planta de Vaso Grande',
    category: 'decor',
    width: 1,
    height: 2,
    isObstacle: true,
    spriteKey: 'plant_pot_large',
    iconColor: '#2b8a3e',
  },
  {
    id: 'bookshelf_wood',
    name: 'Estante de Livros',
    category: 'decor',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'bookshelf_wood',
    iconColor: '#a61e4d',
  },
]
