import { FurnitureDefinition } from '../types/map'

export const TILE_SIZE = 32

export const DEFAULT_AVATAR = {
  skinTone: '#ffd1a4',
  skinColor: '#ffd1a4',
  skinDetail: 'vitiligo1' as const,
  hairStyle: 'messy' as const,
  hairColor: '#2b2b2b',
  facialHair: 'none' as const,
  facialHairColor: '#2b2b2b',
  topType: 'kimono' as const,
  shirtType: 'kimono' as const,
  topColor: '#212529',
  shirtColor: '#212529',
  jacketType: 'none' as const,
  jacketColor: '#4c6ef5',
  bottomType: 'kimono_skirt' as const,
  bottomColor: '#212529',
  pantsColor: '#212529',
  shoesType: 'sandals' as const,
  shoesColor: '#51cf66',
  hatType: 'none' as const,
  hatColor: '#fa5252',
  glassesType: 'none' as const,
  glassesColor: '#343a40',
  accessory: 'none' as const,
  accessoryColor: '#20c997',
  otherType: 'none' as const,
  otherColor: '#20c997',
}

export const FURNITURE_CATALOG: FurnitureDefinition[] = [
  // --- HABBO HOTEL ICONIC CATALOG (FURNI & RARES) ---
  {
    id: 'habbo_sofa_hc',
    name: 'Sofá de Clube HC (Habbo Club)',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_sofa_hc',
    iconColor: '#2b8a3e',
  },
  {
    id: 'habbo_dragon_lamp',
    name: 'Candeeiro Dragão de Fogo (Raro)',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_dragon_lamp',
    iconColor: '#e03131',
  },
  {
    id: 'habbo_duck_yellow',
    name: 'Pato Amarelo Habbo Clássico',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_duck_yellow',
    iconColor: '#fcc419',
  },
  {
    id: 'habbo_executive_desk',
    name: 'Mesa Executiva Habbo (Mogno)',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_executive_desk',
    iconColor: '#5c3a21',
  },
  {
    id: 'habbo_bar_counter',
    name: 'Balcão de Recepção / Bar Habbo',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_bar_counter',
    iconColor: '#a65228',
  },
  {
    id: 'habbo_drink_vending',
    name: 'Máquina de Refrigerante Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_drink_vending',
    iconColor: '#1971c2',
  },
  {
    id: 'habbo_teleport_door',
    name: 'Porta Teletransporte Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_teleport_door',
    iconColor: '#862e9c',
  },
  {
    id: 'habbo_plant_yucca',
    name: 'Planta Yucca Habbo Clássica',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_plant_yucca',
    iconColor: '#2f9e44',
  },
  {
    id: 'habbo_dj_deck',
    name: 'Cabine de DJ Habbo Sound',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_dj_deck',
    iconColor: '#be4bdb',
  },
  {
    id: 'habbo_pool_lounger',
    name: 'Espreguiçadeira de Piscina Habbo',
    category: 'habbo',
    width: 1,
    height: 2,
    isObstacle: false,
    spriteKey: 'habbo_pool_lounger',
    iconColor: '#38d9a9',
  },
  {
    id: 'habbo_tv_retro',
    name: 'TV de Tubo Retrô Habbo',
    category: 'habbo',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'habbo_tv_retro',
    iconColor: '#495057',
  },
  {
    id: 'habbo_sofa_plasto',
    name: 'Sofá Plasto Habbo Azul',
    category: 'habbo',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'habbo_sofa_plasto',
    iconColor: '#339af0',
  },

  // --- DESKS & WORKSPACES ---
  {
    id: 'desk_pc_single',
    name: 'Mesa com PC & Monitor',
    category: 'desks',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_pc_single',
    iconColor: '#4c6ef5',
  },
  {
    id: 'desk_mac_dual',
    name: 'Mesa Apple Dual Monitor',
    category: 'desks',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_mac_dual',
    iconColor: '#748ffc',
  },
  {
    id: 'desk_gamer_triple',
    name: 'Setup Gamer Triplo RGB',
    category: 'desks',
    width: 3,
    height: 2,
    isObstacle: true,
    spriteKey: 'desk_gamer_triple',
    iconColor: '#f06595',
  },
  {
    id: 'desk_simple_wood',
    name: 'Mesa de Madeira Simples',
    category: 'desks',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'desk_simple_wood',
    iconColor: '#d9480f',
  },

  // --- CHAIRS ---
  {
    id: 'chair_office_black',
    name: 'Cadeira de Escritório',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_office_black',
    iconColor: '#495057',
  },
  {
    id: 'chair_gamer_red',
    name: 'Cadeira Gamer Vermelha',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_gamer_red',
    iconColor: '#ff6b6b',
  },
  {
    id: 'chair_wooden',
    name: 'Cadeira de Madeira',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_wooden',
    iconColor: '#f59f00',
  },

  // --- MEETING & COLLABORATION ---
  {
    id: 'table_meeting_large',
    name: 'Mesa de Reunião Grande',
    category: 'meeting',
    width: 4,
    height: 2,
    isObstacle: true,
    spriteKey: 'table_meeting_large',
    iconColor: '#339af0',
  },
  {
    id: 'table_meeting_round',
    name: 'Mesa de Reunião Redonda',
    category: 'meeting',
    width: 2,
    height: 2,
    isObstacle: true,
    spriteKey: 'table_meeting_round',
    iconColor: '#22b8cf',
  },
  {
    id: 'whiteboard_stand',
    name: 'Quadro Branco / Lousa',
    category: 'meeting',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'whiteboard_stand',
    iconColor: '#f8f9fa',
  },
  {
    id: 'tv_presentation',
    name: 'Smart TV Apresentação',
    category: 'meeting',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'tv_presentation',
    iconColor: '#1098ad',
  },

  // --- LOUNGE & RELAX ---
  {
    id: 'sofa_orange_3seat',
    name: 'Sofá Laranja 3 Lugares',
    category: 'lounge',
    width: 3,
    height: 1,
    isObstacle: false,
    spriteKey: 'sofa_orange_3seat',
    iconColor: '#fd7e14',
  },
  {
    id: 'sofa_blue_2seat',
    name: 'Sofá Azul 2 Lugares',
    category: 'lounge',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'sofa_blue_2seat',
    iconColor: '#4dabf7',
  },
  {
    id: 'beanbag_purple',
    name: 'Puff Roxo Conforto',
    category: 'lounge',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'beanbag_purple',
    iconColor: '#be4bdb',
  },
  {
    id: 'coffee_table_round',
    name: 'Mesa de Centro',
    category: 'lounge',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'coffee_table_round',
    iconColor: '#e8590c',
  },
  {
    id: 'ping_pong_table',
    name: 'Mesa de Ping Pong',
    category: 'lounge',
    width: 3,
    height: 2,
    isObstacle: true,
    spriteKey: 'ping_pong_table',
    iconColor: '#40c057',
  },

  // --- WALL DECORS & WINDOWS (ITENS DE PAREDE) ---
  {
    id: 'window_grid_large',
    name: 'Janela Panorâmica Quadriculada (3x1)',
    category: 'walls_windows',
    width: 3,
    height: 1,
    isObstacle: false,
    spriteKey: 'window_grid_large',
    iconColor: '#38bdf8',
  },
  {
    id: 'window_grid_medium',
    name: 'Janela de Escritório (2x1)',
    category: 'walls_windows',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'window_grid_medium',
    iconColor: '#38bdf8',
  },
  {
    id: 'wall_cabinets_kitchen',
    name: 'Armários Suspensos de Café/Cozinha (3x1)',
    category: 'walls_windows',
    width: 3,
    height: 1,
    isObstacle: false,
    spriteKey: 'wall_cabinets_kitchen',
    iconColor: '#475569',
  },
  {
    id: 'wall_whiteboard',
    name: 'Quadro Branco de Parede (2x1)',
    category: 'walls_windows',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'wall_whiteboard',
    iconColor: '#f8fafc',
  },
  {
    id: 'wall_tv_large',
    name: 'TV / Painel de Parede (2x1)',
    category: 'walls_windows',
    width: 2,
    height: 1,
    isObstacle: false,
    spriteKey: 'wall_tv_large',
    iconColor: '#0f172a',
  },
  {
    id: 'wall_clock_modern',
    name: 'Relógio de Parede (1x1)',
    category: 'walls_windows',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'wall_clock_modern',
    iconColor: '#e2e8f0',
  },
  {
    id: 'wall_poster_habbo',
    name: 'Quadro Decorativo Habbo (1x1)',
    category: 'walls_windows',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'wall_poster_habbo',
    iconColor: '#fab005',
  },

  // --- MODERN GATHER OFFICE FURNITURE ---
  {
    id: 'desk_executive_clean',
    name: 'Mesa de Reunião / Escritório Clean (3x1)',
    category: 'desks',
    width: 3,
    height: 1,
    isObstacle: true,
    spriteKey: 'desk_executive_clean',
    iconColor: '#e2e8f0',
  },
  {
    id: 'chair_office_mesh',
    name: 'Cadeira de Escritório Ergonômica Mesh',
    category: 'chairs',
    width: 1,
    height: 1,
    isObstacle: false,
    spriteKey: 'chair_office_mesh',
    iconColor: '#334155',
  },
  {
    id: 'potted_bonsai_tree',
    name: 'Vaso de Árvore Bonsai de Canto',
    category: 'decor',
    width: 1,
    height: 1,
    isObstacle: true,
    spriteKey: 'potted_bonsai_tree',
    iconColor: '#4ade80',
  },
  {
    id: 'coffee_bar_station',
    name: 'Balcão de Café com Cafeteira & Xícaras (3x1)',
    category: 'decor',
    width: 3,
    height: 1,
    isObstacle: true,
    spriteKey: 'coffee_bar_station',
    iconColor: '#7c3aed',
  },
  {
    id: 'bookshelf_arcade',
    name: 'Estante de Livros & Arcade Gamer (2x1)',
    category: 'decor',
    width: 2,
    height: 1,
    isObstacle: true,
    spriteKey: 'bookshelf_arcade',
    iconColor: '#f59e0b',
  },
]
